nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'http://localhost:5173', 'http://localhost:5174','http://localhost:5175', 'http://localhost:8000']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        expose_headers: ['Link', 'Content-Type']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600
